# Generated by Django 3.1.4 on 2020-12-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('name', models.TextField()),
                ('gender', models.TextField()),
                ('age', models.TextField()),
            ],
        ),
    ]
