# Generated by Django 3.1.4 on 2020-12-04 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_side_encryption', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Individuals',
            new_name='Individual',
        ),
    ]
