# Generated by Django 3.1.4 on 2020-12-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side_encryption', '0002_auto_20201204_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='individual',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
