# Generated by Django 3.1.4 on 2020-12-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side_encryption', '0003_auto_20201204_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
