# Generated by Django 3.1.4 on 2020-12-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side_encryption', '0004_auto_20201204_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='individual',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
