# Generated by Django 3.1.4 on 2020-12-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_side_encryption', '0005_auto_20201204_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='age',
        ),
    ]
