# Generated by Django 3.1.4 on 2020-12-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side_encryption', '0006_remove_individual_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='age',
            field=models.DecimalField(decimal_places=0, default=20, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='individual',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
