# Generated by Django 3.1.4 on 2020-12-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side_encryption', '0007_auto_20201204_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='individual',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
